#!/bin/bash

for file in $(find symlinks -type f -maxdepth 1); do
  dotfile=${file/symlinks\//.}
  echo -e "  Installing $dotfile..."

  ln -sf "$PWD/$file" "$HOME/$dotfile"
done

path="$PWD/init.sh"
profile="$HOME/.profile"
grep -q "$path" $profile || (echo "Loading 'init.sh' on your '.profile'." && echo -e "\nsource $path" >> $profile)

source $profile
echo "Done!"
