format = "${custom.zap_emoji}${custom.work_emoji}$directory$elixir$ruby$git_branch$git_state$line_break$character"

[custom.zap_emoji]
command = "echo ⚡"
when = """ git config user.email | grep -q "lucasmazza@hey.com" """

[custom.work_emoji]
command = "echo 🏢"
when = """ git config user.email | grep -q "lucas@remote.com" """

[character]
success_symbol = '[\$](fg:#000000)'
error_symbol = '[\$](bold fg:#d73a49)'

[directory]
format = "[$path](fg:#000000) "
truncate_to_repo = false

[git_branch]
format = '[\($branch\)](bold fg:#dbab09)'

[elixir]
format = "| [$version](bold fg:#6f42c1) "

[ruby]
format = "| [$version](bold fg:#d73a49) "
