format = "${custom.emoji}$directory$elixir$ruby$git_branch$git_state$line_break$character"

[custom.emoji]
command = "if [ -n $(git config user.email | grep hey) ]; then echo -n '⚡'; else echo -n '🏢'; fi"
files = [".gitignore", ".DS_Store"]

[character]
success_symbol = '[\$](fg:#000000)'
error_symbol = '[\$](bold fg:#d73a49)'

[directory]
format = "[$path](fg:#000000) "
truncate_to_repo = false

[git_branch]
format = '[\($branch\)](bold fg:#dbab09)'

[elixir]
format = "| [$version](bold fg:#6f42c1) "

[ruby]
format = "| [$version](bold fg:#d73a49) "
