#!/usr/bin/env bash

# Save screenshots in ~/Screenshots folder
mkdir -p $HOME/Screenshots
defaults write com.apple.screencapture location -string "$HOME/Screenshots"

# Check for software updates daily, not just once per week
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
