#!/bin/bash
__dir__="$(git rev-parse --absolute-git-dir | sed 's/\/.git//')"

link_files() {
  local root=$1;
  local destination=$HOME;

  if [ ! -d "$root/symlinks" ]; then
    return 1
  fi

  for file in $(find $root/symlinks -type f -maxdepth 3); do
    filename=${file/$root\/symlinks\//.}
    src=${file/$HOME/"~"}
    echo "🔗  Linking '$src'..."

    mkdir -p $(dirname "$destination/$filename")
    ln -sf $file "$destination/$filename"
  done
}

inject_init() {
  local init="$__dir__/init.zsh"
  local profile="$HOME/.zshrc"

  touch $profile

  if ! grep -q "lucasmazza/dotfiles" $profile; then
    echo "👉 Loading 'init.zsh' on  your '~/.zshrc'..."
    echo -e "# Added by lucasmazza/dotfiles\ntest -f $init && source $init\n" >> $profile
  fi
}

create_directories() {
  echo "👉 Creating directories on '~/src'..."
  mkdir -p $HOME/src/{me,oss,work}
}

link_files $__dir__
link_files "$HOME/Dropbox"
inject_init
create_directories

. $__dir__/script/macos-custom

echo "🎉  Done!"
